### ISSUE TITLE
Perf-test: option to ignore the committed offset

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-stream-java-client#6]
Currently if an offset has been committed, there is no way to use any other offset - any `--offset` specification will be overridden and the previously committed offset will be used instead. For testing purposes, it's nice to be able to use an arbitrary offset.

Options:
1. Additional option to force `--offset` to be used
2. Option to use a different consumer name so that no committed offset is found for this consumer

If option 2 is selected, perhaps a random/GUID based value should be possible to allow easy idempotent tests where we can easily execute a new scenario without worrying that only a part of the stream will be used in the test due to an offset committed previously.

**Comment by acogoluegnes** [comment]
I would go with 2 and suggest something like for [streams](https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/#streams) to define consumer names precisely and a shortcut to have random consumer names.

 * `--consumer-names uuid` would give something like `7cc75659-ea67-4874-96ef-151a505e1a55`
 * `--consumer-names stream-%s-consumer-%d` would give `stream-stream-consumer-1` for the first consumer on the `stream` stream
 * the default would be `%s-%d`, that is `stream-1` for the first consumer on the `stream` stream. This would change from the current default, which starts at 0, but this is for consistency with stream naming.

For the pattern form, the arguments would be first the stream and then the consumer number, so that would work for patterns like `stream-%s-consumer-%d`. For patterns where the number should go first, the parameter would need to use indexes, that `1$` for the stream name and `2$` for the consumer number, e.g. `consumer-%2$d-on-stream-%1$s`, which would translate to `consumer-0-on-stream-stream`.
